// <auto-generated />
using System;
using Forum.App.Data;
using Forum.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forum.App.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20230601134400_CreateAndSeedDb")]
    partial class CreateAndSeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forum.App.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("03741c5a-0190-4b02-9f26-1161b2cf6edc"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean elementum rhoncus nunc sed ullamcorper. Sed sed urna pellentesque, placerat augue.",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("b8739324-c93a-4a69-aa1e-9d235a2c0279"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut enim non nibh euismod pretium. Ut malesuada nulla ut mattis.",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("29e0f3dd-d731-43a0-93e0-0b65e95fcfa6"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In faucibus nunc nec augue congue tincidunt. Donec tristique, leo sollicitudin dignissim.",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
